[package]
name = "fb2lib"
version = "0.4.5"
authors = ["seb-odessa <seb@ukr.net>"]

[lib]
name = "lib"
path = "src/lib/lib.rs"

[dependencies]
    zip = "*"
    rusqlite = "*"
    time = "0.1.38"
    clap = "2.26.2"
    regex = "0.2.2"
    xmltree = "*"




