[package]
name = "fb2lib"
version = "0.1.0"
authors = ["seb-odessa <seb@ukr.net>"]

[lib]
name = "lib"
path = "src/lib/lib.rs"

[dependencies]
    zip = "0.2.3"
    rusqlite = "*"
    time = "*"
    clap = "*"
    regex = "*"
    fb2parser = { git = "https://github.com/seb-odessa/fb2parser.git" }

